// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#include "../ui.h"

void ui_attitude_indicator_screen_init(void)
{
    ui_attitude_indicator = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_attitude_indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_attitude_indicator);
    lv_img_set_src(ui_Image1, &ui_img_978830312);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_attitude_indicator);
    lv_img_set_src(ui_Image2, &ui_img_attitude_foreground_1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_Image2, 42);
    lv_obj_set_y(ui_Image2, 398);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rot = lv_arc_create(ui_attitude_indicator);
    lv_obj_set_width(ui_rot, 240);
    lv_obj_set_height(ui_rot, 240);
    lv_obj_set_align(ui_rot, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_rot, -360, 360);
    lv_arc_set_value(ui_rot, 180);
    lv_arc_set_bg_angles(ui_rot, 240, 300);
    lv_arc_set_mode(ui_rot, LV_ARC_MODE_SYMMETRICAL);
    lv_obj_set_style_arc_color(ui_rot, lv_color_hex(0x01FD72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_rot, lv_color_hex(0x40FF83), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rot, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_rot, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_rot, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rot, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rot, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_attitude_indicator);
    lv_img_set_src(ui_Image3, &ui_img_attitude_foreground_1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 164
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 155
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -50);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_accellerationbar = lv_bar_create(ui_attitude_indicator);
    lv_bar_set_mode(ui_accellerationbar, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_accellerationbar, -50, 50);
    lv_bar_set_value(ui_accellerationbar, -50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_accellerationbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_accellerationbar, 7);
    lv_obj_set_height(ui_accellerationbar, 55);
    lv_obj_set_x(ui_accellerationbar, 50);
    lv_obj_set_y(ui_accellerationbar, 0);
    lv_obj_set_align(ui_accellerationbar, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_accellerationbar, lv_color_hex(0x0080FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_accellerationbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_accellerationbar, lv_color_hex(0x00FE72), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_accellerationbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblThousandsHt = lv_label_create(ui_attitude_indicator);
    lv_obj_set_width(ui_lblThousandsHt, 37);
    lv_obj_set_height(ui_lblThousandsHt, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_lblThousandsHt, 72);
    lv_obj_set_y(ui_lblThousandsHt, 0);
    lv_obj_set_align(ui_lblThousandsHt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblThousandsHt, "00");
    lv_obj_set_style_text_color(ui_lblThousandsHt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblThousandsHt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblThousandsHt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblThousandsHt, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblThousandsHt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblThousandsHt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblThousandsHt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblThousandsHt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblThousandsHt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUnitsHt = lv_label_create(ui_attitude_indicator);
    lv_obj_set_width(ui_lblUnitsHt, 30);
    lv_obj_set_height(ui_lblUnitsHt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnitsHt, 105);
    lv_obj_set_y(ui_lblUnitsHt, 0);
    lv_obj_set_align(ui_lblUnitsHt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnitsHt, "000");
    lv_obj_set_style_text_color(ui_lblUnitsHt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblUnitsHt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblUnitsHt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblUnitsHt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblUnitsHt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblUnitsHt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblUnitsHt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblUnitsHt, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGS = lv_label_create(ui_attitude_indicator);
    lv_obj_set_width(ui_lblGS, 49);
    lv_obj_set_height(ui_lblGS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGS, -95);
    lv_obj_set_y(ui_lblGS, 0);
    lv_obj_set_align(ui_lblGS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGS, "000");
    lv_obj_set_style_text_color(ui_lblGS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblGS, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblGS, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblGS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblGS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblGS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lblGS, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcCPAcc = lv_arc_create(ui_attitude_indicator);
    lv_obj_set_width(ui_ArcCPAcc, 240);
    lv_obj_set_height(ui_ArcCPAcc, 240);
    lv_obj_set_align(ui_ArcCPAcc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcCPAcc, -30, 30);
    lv_arc_set_value(ui_ArcCPAcc, 15);
    lv_arc_set_bg_angles(ui_ArcCPAcc, 60, 120);
    lv_arc_set_mode(ui_ArcCPAcc, LV_ARC_MODE_SYMMETRICAL);
    lv_obj_set_style_arc_color(ui_ArcCPAcc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcCPAcc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcCPAcc, lv_color_hex(0xFFFD40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcCPAcc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcCPAcc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcCPAcc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcCPAcc, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcCPAcc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblCRS = lv_label_create(ui_attitude_indicator);
    lv_obj_set_width(ui_lblCRS, 51);
    lv_obj_set_height(ui_lblCRS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCRS, 0);
    lv_obj_set_y(ui_lblCRS, -90);
    lv_obj_set_align(ui_lblCRS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCRS, "000");
    lv_obj_set_style_text_color(ui_lblCRS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCRS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblCRS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCRS, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblCRS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblCRS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblCRS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblCRS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblCRS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

}
