// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#include "../ui.h"

void ui_gmeter_screen_init(void)
{
    ui_gmeter = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_gmeter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gmeterbkgnd = lv_img_create(ui_gmeter);
    lv_img_set_src(ui_gmeterbkgnd, &ui_img_gmeterbackground_png);
    lv_obj_set_width(ui_gmeterbkgnd, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_gmeterbkgnd, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(ui_gmeterbkgnd, -1);
    lv_obj_set_y(ui_gmeterbkgnd, 0);
    lv_obj_set_align(ui_gmeterbkgnd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gmeterbkgnd, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gmeterbkgnd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reset = lv_btn_create(ui_gmeter);
    lv_obj_set_width(ui_reset, 75);
    lv_obj_set_height(ui_reset, 37);
    lv_obj_set_x(ui_reset, -1);
    lv_obj_set_y(ui_reset, 47);
    lv_obj_set_align(ui_reset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_reset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_reset, lv_color_hex(0x414040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_reset, lv_color_hex(0xE3E3E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_reset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_reset, lv_color_hex(0xF1EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zeropointers = lv_label_create(ui_gmeter);
    lv_obj_set_width(ui_zeropointers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zeropointers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zeropointers, -1);
    lv_obj_set_y(ui_zeropointers, 48);
    lv_obj_set_align(ui_zeropointers, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zeropointers, "RESET");
    lv_obj_set_style_text_color(ui_zeropointers, lv_color_hex(0xE9E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zeropointers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maxgpointer = lv_img_create(ui_gmeter);
    lv_img_set_src(ui_maxgpointer, &ui_img_gpointer_png);
    lv_obj_set_width(ui_maxgpointer, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_maxgpointer, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_maxgpointer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_maxgpointer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_maxgpointer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mingpointer = lv_img_create(ui_gmeter);
    lv_img_set_src(ui_mingpointer, &ui_img_gpointer_png);
    lv_obj_set_width(ui_mingpointer, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_mingpointer, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(ui_mingpointer, -2);
    lv_obj_set_y(ui_mingpointer, 0);
    lv_obj_set_align(ui_mingpointer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mingpointer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mingpointer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpointer = lv_img_create(ui_gmeter);
    lv_img_set_src(ui_gpointer, &ui_img_gpointer_png);
    lv_obj_set_width(ui_gpointer, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_gpointer, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_gpointer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gpointer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gpointer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_gmeterbkgnd, ui_event_gmeterbkgnd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_reset, ui_event_reset, LV_EVENT_ALL, NULL);

}
