// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#include "../ui.h"

void ui_setup_screen_init(void)
{
    ui_setup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setup, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCalibrate = lv_btn_create(ui_setup);
    lv_obj_set_width(ui_btnCalibrate, 89);
    lv_obj_set_height(ui_btnCalibrate, 35);
    lv_obj_set_x(ui_btnCalibrate, -49);
    lv_obj_set_y(ui_btnCalibrate, 64);
    lv_obj_set_align(ui_btnCalibrate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCalibrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCalibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnCalibrate, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnCalibrate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnCalibrate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblcalibrate = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblcalibrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblcalibrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblcalibrate, -47);
    lv_obj_set_y(ui_lblcalibrate, 65);
    lv_obj_set_align(ui_lblcalibrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblcalibrate, "CAL IMU");
    lv_obj_set_style_text_color(ui_lblcalibrate, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblcalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSleep = lv_btn_create(ui_setup);
    lv_obj_set_width(ui_btnSleep, 88);
    lv_obj_set_height(ui_btnSleep, 35);
    lv_obj_set_x(ui_btnSleep, 49);
    lv_obj_set_y(ui_btnSleep, 64);
    lv_obj_set_align(ui_btnSleep, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSleep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSleep, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSleep, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSleep, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSleep = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblSleep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSleep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSleep, 48);
    lv_obj_set_y(ui_lblSleep, 64);
    lv_obj_set_align(ui_lblSleep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSleep, "SLEEP");
    lv_obj_set_style_text_color(ui_lblSleep, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVolts = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblVolts, 33);
    lv_obj_set_height(ui_lblVolts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVolts, -19);
    lv_obj_set_y(ui_lblVolts, 102);
    lv_obj_set_align(ui_lblVolts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVolts, " 3.75");
    lv_obj_set_style_text_color(ui_lblVolts, lv_color_hex(0xF8F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVolts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblVolts, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtVolts = lv_label_create(ui_setup);
    lv_obj_set_width(ui_txtVolts, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtVolts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtVolts, 21);
    lv_obj_set_y(ui_txtVolts, 102);
    lv_obj_set_align(ui_txtVolts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtVolts, "Volts");
    lv_obj_set_style_text_color(ui_txtVolts, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtVolts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblsysnctime = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblsysnctime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblsysnctime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblsysnctime, 2);
    lv_obj_set_y(ui_lblsysnctime, -96);
    lv_obj_set_align(ui_lblsysnctime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblsysnctime, "UTC\nOffset");
    lv_obj_set_style_text_color(ui_lblsysnctime, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblsysnctime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblsysnctime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnplus1hr = lv_btn_create(ui_setup);
    lv_obj_set_width(ui_btnplus1hr, 40);
    lv_obj_set_height(ui_btnplus1hr, 35);
    lv_obj_set_x(ui_btnplus1hr, -50);
    lv_obj_set_y(ui_btnplus1hr, -85);
    lv_obj_set_align(ui_btnplus1hr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnplus1hr, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnplus1hr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnplus1hr, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnplus1hr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnplus1hr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnplus1hr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnplus1hr, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnminus1hr = lv_btn_create(ui_setup);
    lv_obj_set_width(ui_btnminus1hr, 36);
    lv_obj_set_height(ui_btnminus1hr, 35);
    lv_obj_set_x(ui_btnminus1hr, 52);
    lv_obj_set_y(ui_btnminus1hr, -84);
    lv_obj_set_align(ui_btnminus1hr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnminus1hr, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnminus1hr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnminus1hr, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnminus1hr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnminus1hr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnminus1hr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnminus1hr, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txttimeplus = lv_label_create(ui_setup);
    lv_obj_set_width(ui_txttimeplus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txttimeplus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txttimeplus, -50);
    lv_obj_set_y(ui_txttimeplus, -84);
    lv_obj_set_align(ui_txttimeplus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txttimeplus, "+");
    lv_obj_set_style_text_color(ui_txttimeplus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txttimeplus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbltimeminus = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lbltimeminus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltimeminus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltimeminus, 50);
    lv_obj_set_y(ui_lbltimeminus, -84);
    lv_obj_set_align(ui_lbltimeminus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbltimeminus, "-");
    lv_obj_set_style_text_color(ui_lbltimeminus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbltimeminus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblhours = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblhours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblhours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblhours, -11);
    lv_obj_set_y(ui_lblhours, -71);
    lv_obj_set_align(ui_lblhours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblhours, "+0");
    lv_obj_set_style_text_color(ui_lblhours, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblhours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblfromgmt = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblfromgmt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblfromgmt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblfromgmt, 14);
    lv_obj_set_y(ui_lblfromgmt, -71);
    lv_obj_set_align(ui_lblfromgmt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblfromgmt, "hrs");
    lv_obj_set_style_text_color(ui_lblfromgmt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblfromgmt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtGPSspeed = lv_label_create(ui_setup);
    lv_obj_set_width(ui_txtGPSspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtGPSspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtGPSspeed, -75);
    lv_obj_set_y(ui_txtGPSspeed, -31);
    lv_obj_set_align(ui_txtGPSspeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtGPSspeed, "GPS Speed");
    lv_obj_set_style_text_color(ui_txtGPSspeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtGPSspeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtGPScrs = lv_label_create(ui_setup);
    lv_obj_set_width(ui_txtGPScrs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtGPScrs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtGPScrs, -64);
    lv_obj_set_y(ui_txtGPScrs, -49);
    lv_obj_set_align(ui_txtGPScrs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtGPScrs, "GPS Crs");
    lv_obj_set_style_text_color(ui_txtGPScrs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtGPScrs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSpeed = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSpeed, -8);
    lv_obj_set_y(ui_lblSpeed, -30);
    lv_obj_set_align(ui_lblSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeed, "000.0");
    lv_obj_set_style_text_color(ui_lblSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCrs = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblCrs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCrs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCrs, -8);
    lv_obj_set_y(ui_lblCrs, -47);
    lv_obj_set_align(ui_lblCrs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCrs, "000.0");
    lv_obj_set_style_text_color(ui_lblCrs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCrs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtAcc = lv_label_create(ui_setup);
    lv_obj_set_width(ui_txtAcc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtAcc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtAcc, 44);
    lv_obj_set_y(ui_txtAcc, -48);
    lv_obj_set_align(ui_txtAcc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtAcc, "Acc'n");
    lv_obj_set_style_text_color(ui_txtAcc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtAcc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtCAcc = lv_label_create(ui_setup);
    lv_obj_set_width(ui_txtCAcc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtCAcc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtCAcc, 43);
    lv_obj_set_y(ui_txtCAcc, -30);
    lv_obj_set_align(ui_txtCAcc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtCAcc, "C'Acc");
    lv_obj_set_style_text_color(ui_txtCAcc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtCAcc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAcceleration = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblAcceleration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAcceleration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAcceleration, 89);
    lv_obj_set_y(ui_lblAcceleration, -47);
    lv_obj_set_align(ui_lblAcceleration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAcceleration, "00.00");
    lv_obj_set_style_text_color(ui_lblAcceleration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAcceleration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCenplAc = lv_label_create(ui_setup);
    lv_obj_set_width(ui_lblCenplAc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCenplAc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCenplAc, 89);
    lv_obj_set_y(ui_lblCenplAc, -29);
    lv_obj_set_align(ui_lblCenplAc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCenplAc, "0.000");
    lv_obj_set_style_text_color(ui_lblCenplAc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCenplAc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnCalibrate, ui_event_btnCalibrate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSleep, ui_event_btnSleep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnplus1hr, ui_event_btnplus1hr, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnminus1hr, ui_event_btnminus1hr, LV_EVENT_ALL, NULL);

}
