// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#ifndef _GMETER_UI_H
#define _GMETER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_gmeter
void ui_gmeter_screen_init(void);
extern lv_obj_t * ui_gmeter;
void ui_event_gmeterbkgnd(lv_event_t * e);
extern lv_obj_t * ui_gmeterbkgnd;
void ui_event_reset(lv_event_t * e);
extern lv_obj_t * ui_reset;
extern lv_obj_t * ui_zeropointers;
extern lv_obj_t * ui_maxgpointer;
extern lv_obj_t * ui_mingpointer;
extern lv_obj_t * ui_gpointer;
// SCREEN: ui_attitude_indicator
void ui_attitude_indicator_screen_init(void);
extern lv_obj_t * ui_attitude_indicator;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_rot;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_accellerationbar;
extern lv_obj_t * ui_lblThousandsHt;
extern lv_obj_t * ui_lblUnitsHt;
extern lv_obj_t * ui_lblGS;
extern lv_obj_t * ui_ArcCPAcc;
extern lv_obj_t * ui_lblCRS;
// SCREEN: ui_watch
void ui_watch_screen_init(void);
extern lv_obj_t * ui_watch;
extern lv_obj_t * ui_watchface;
extern lv_obj_t * ui_hourhand;
extern lv_obj_t * ui_minhand;
extern lv_obj_t * ui_sechand;
// SCREEN: ui_aoa
void ui_aoa_screen_init(void);
extern lv_obj_t * ui_aoa;
extern lv_obj_t * ui_aoabackground;
extern lv_obj_t * ui_AOAneedle;
extern lv_obj_t * ui_imgnegindexer;
extern lv_obj_t * ui_imglowersemicircle;
extern lv_obj_t * ui_imguppersemicircle;
extern lv_obj_t * ui_imgyellowchevron;
extern lv_obj_t * ui_imgredchevron;
extern lv_obj_t * ui_imggreentriangle;
// SCREEN: ui_setup
void ui_setup_screen_init(void);
extern lv_obj_t * ui_setup;
void ui_event_btnCalibrate(lv_event_t * e);
extern lv_obj_t * ui_btnCalibrate;
extern lv_obj_t * ui_lblcalibrate;
void ui_event_btnSleep(lv_event_t * e);
extern lv_obj_t * ui_btnSleep;
extern lv_obj_t * ui_lblSleep;
extern lv_obj_t * ui_lblVolts;
extern lv_obj_t * ui_txtVolts;
extern lv_obj_t * ui_lblsysnctime;
void ui_event_btnplus1hr(lv_event_t * e);
extern lv_obj_t * ui_btnplus1hr;
void ui_event_btnminus1hr(lv_event_t * e);
extern lv_obj_t * ui_btnminus1hr;
extern lv_obj_t * ui_txttimeplus;
extern lv_obj_t * ui_lbltimeminus;
extern lv_obj_t * ui_lblhours;
extern lv_obj_t * ui_lblfromgmt;
extern lv_obj_t * ui_txtGPSspeed;
extern lv_obj_t * ui_txtGPScrs;
extern lv_obj_t * ui_lblSpeed;
extern lv_obj_t * ui_lblCrs;
extern lv_obj_t * ui_txtAcc;
extern lv_obj_t * ui_txtCAcc;
extern lv_obj_t * ui_lblAcceleration;
extern lv_obj_t * ui_lblCenplAc;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_gmeterbackground_png);    // assets/gmeterbackground.png
LV_IMG_DECLARE(ui_img_gpointer_png);    // assets/gpointer.png
LV_IMG_DECLARE(ui_img_978830312);    // assets/horizon_GA_elec_flag-1.png
LV_IMG_DECLARE(ui_img_attitude_foreground_1_png);    // assets/attitude_foreground_1.png
LV_IMG_DECLARE(ui_img_watchface_png);    // assets/watchface.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_aoa_background_png);    // assets/aoa_background.png
LV_IMG_DECLARE(ui_img_negativeindexer_png);    // assets/negativeindexer.png
LV_IMG_DECLARE(ui_img_lowersemicircle_png);    // assets/lowersemicircle.png
LV_IMG_DECLARE(ui_img_uppersemicircle_png);    // assets/uppersemicircle.png
LV_IMG_DECLARE(ui_img_yellowchevron_png);    // assets/yellowchevron.png
LV_IMG_DECLARE(ui_img_redchevron_png);    // assets/redchevron.png
LV_IMG_DECLARE(ui_img_green_triangle_png);    // assets/green triangle.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
