// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void reset_pointers(lv_event_t * e);
void restartESP(lv_event_t * e);
void sleepall(lv_event_t * e);
void time_plus(lv_event_t * e);
void time_minus(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
