// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#include "ui.h"

int reset_minmax = 0;
int re_start = 0;
int gotosleep = 0;
int synctime = 0;
int timeplusonehr = 0;
int timeminusonehr = 0;

void reset_pointers(lv_event_t * e)
{
	reset_minmax = 1;
}

void restartESP(lv_event_t * e)
{
	re_start = 1;

}

void sleepall(lv_event_t * e)
{
	gotosleep = 1;
}

void sync_time(lv_event_t * e)
{
	synctime = 1;
}

void time_plus(lv_event_t * e)
{
	timeplusonehr = 1;
}

void time_minus(lv_event_t * e)
{
	timeminusonehr = 1;
}
