// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#include "../ui.h"

void ui_aoa_screen_init(void)
{
    ui_aoa = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_aoa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aoabackground = lv_img_create(ui_aoa);
    lv_img_set_src(ui_aoabackground, &ui_img_aoa_background_png);
    lv_obj_set_width(ui_aoabackground, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_aoabackground, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_aoabackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aoabackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aoabackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AOAneedle = lv_img_create(ui_aoa);
    lv_img_set_src(ui_AOAneedle, &ui_img_gpointer_png);
    lv_obj_set_width(ui_AOAneedle, lv_pct(100));
    lv_obj_set_height(ui_AOAneedle, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_align(ui_AOAneedle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AOAneedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AOAneedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_AOAneedle, -900);

    ui_imgnegindexer = lv_img_create(ui_aoa);
    lv_img_set_src(ui_imgnegindexer, &ui_img_negativeindexer_png);
    lv_obj_set_width(ui_imgnegindexer, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imgnegindexer, LV_SIZE_CONTENT);    /// 101
    lv_obj_set_x(ui_imgnegindexer, -66);
    lv_obj_set_y(ui_imgnegindexer, -7);
    lv_obj_set_align(ui_imgnegindexer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgnegindexer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgnegindexer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imglowersemicircle = lv_img_create(ui_aoa);
    lv_img_set_src(ui_imglowersemicircle, &ui_img_lowersemicircle_png);
    lv_obj_set_width(ui_imglowersemicircle, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imglowersemicircle, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_imglowersemicircle, -66);
    lv_obj_set_y(ui_imglowersemicircle, 5);
    lv_obj_set_align(ui_imglowersemicircle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imglowersemicircle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imglowersemicircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imguppersemicircle = lv_img_create(ui_aoa);
    lv_img_set_src(ui_imguppersemicircle, &ui_img_uppersemicircle_png);
    lv_obj_set_width(ui_imguppersemicircle, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imguppersemicircle, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_imguppersemicircle, -66);
    lv_obj_set_y(ui_imguppersemicircle, -17);
    lv_obj_set_align(ui_imguppersemicircle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imguppersemicircle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imguppersemicircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgyellowchevron = lv_img_create(ui_aoa);
    lv_img_set_src(ui_imgyellowchevron, &ui_img_yellowchevron_png);
    lv_obj_set_width(ui_imgyellowchevron, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imgyellowchevron, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_imgyellowchevron, -66);
    lv_obj_set_y(ui_imgyellowchevron, 31);
    lv_obj_set_align(ui_imgyellowchevron, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgyellowchevron, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgyellowchevron, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgredchevron = lv_img_create(ui_aoa);
    lv_img_set_src(ui_imgredchevron, &ui_img_redchevron_png);
    lv_obj_set_width(ui_imgredchevron, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imgredchevron, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_imgredchevron, -66);
    lv_obj_set_y(ui_imgredchevron, -44);
    lv_obj_set_align(ui_imgredchevron, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgredchevron, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgredchevron, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imggreentriangle = lv_img_create(ui_aoa);
    lv_img_set_src(ui_imggreentriangle, &ui_img_green_triangle_png);
    lv_obj_set_width(ui_imggreentriangle, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_imggreentriangle, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_imggreentriangle, -66);
    lv_obj_set_y(ui_imggreentriangle, 69);
    lv_obj_set_align(ui_imggreentriangle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imggreentriangle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imggreentriangle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
