// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_gmeter
void ui_gmeter_screen_init(void);
lv_obj_t * ui_gmeter;
void ui_event_gmeterbkgnd(lv_event_t * e);
lv_obj_t * ui_gmeterbkgnd;
void ui_event_reset(lv_event_t * e);
lv_obj_t * ui_reset;
lv_obj_t * ui_zeropointers;
lv_obj_t * ui_maxgpointer;
lv_obj_t * ui_mingpointer;
lv_obj_t * ui_gpointer;


// SCREEN: ui_attitude_indicator
void ui_attitude_indicator_screen_init(void);
lv_obj_t * ui_attitude_indicator;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_rot;
lv_obj_t * ui_accellerationbar;
lv_obj_t * ui_Image3;
lv_obj_t * ui_lblThousandsHt;
lv_obj_t * ui_lblUnitsHt;
lv_obj_t * ui_lblGS;
lv_obj_t * ui_ArcCPAcc;
lv_obj_t * ui_lblCRS;


// SCREEN: ui_watch
void ui_watch_screen_init(void);
lv_obj_t * ui_watch;
lv_obj_t * ui_watchface;
lv_obj_t * ui_hourhand;
lv_obj_t * ui_minhand;
lv_obj_t * ui_sechand;


// SCREEN: ui_aoa
void ui_aoa_screen_init(void);
lv_obj_t * ui_aoa;
lv_obj_t * ui_aoabackground;
lv_obj_t * ui_AOAneedle;
lv_obj_t * ui_imgnegindexer;
lv_obj_t * ui_imglowersemicircle;
lv_obj_t * ui_imguppersemicircle;
lv_obj_t * ui_imgyellowchevron;
lv_obj_t * ui_imgredchevron;
lv_obj_t * ui_imggreentriangle;


// SCREEN: ui_setup
void ui_setup_screen_init(void);
lv_obj_t * ui_setup;
void ui_event_btnCalibrate(lv_event_t * e);
lv_obj_t * ui_btnCalibrate;
lv_obj_t * ui_lblcalibrate;
void ui_event_btnSleep(lv_event_t * e);
lv_obj_t * ui_btnSleep;
lv_obj_t * ui_lblSleep;
lv_obj_t * ui_lblVolts;
lv_obj_t * ui_txtVolts;
lv_obj_t * ui_lblsysnctime;
void ui_event_btnplus1hr(lv_event_t * e);
lv_obj_t * ui_btnplus1hr;
void ui_event_btnminus1hr(lv_event_t * e);
lv_obj_t * ui_btnminus1hr;
lv_obj_t * ui_txttimeplus;
lv_obj_t * ui_lbltimeminus;
lv_obj_t * ui_lblhours;
lv_obj_t * ui_lblfromgmt;
lv_obj_t * ui_txtGPSspeed;
lv_obj_t * ui_txtGPScrs;
lv_obj_t * ui_lblSpeed;
lv_obj_t * ui_lblCrs;
lv_obj_t * ui_txtAcc;
lv_obj_t * ui_txtCAcc;
lv_obj_t * ui_lblAcceleration;
lv_obj_t * ui_lblCenplAc;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_attitude_foreground_[1] = {&ui_img_attitude_foreground_1_png};
const lv_img_dsc_t * ui_imgset_1997845812[1] = {&ui_img_978830312};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_gmeterbkgnd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_attitude_indicator, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_attitude_indicator_screen_init);
    }
}
void ui_event_reset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        reset_pointers(e);
    }
}
void ui_event_btnCalibrate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        restartESP(e);
    }
}
void ui_event_btnSleep(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        sleepall(e);
    }
}
void ui_event_btnplus1hr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        time_plus(e);
    }
}
void ui_event_btnminus1hr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        time_minus(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_gmeter_screen_init();
    ui_attitude_indicator_screen_init();
    ui_watch_screen_init();
    ui_aoa_screen_init();
    ui_setup_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_gmeter);
}
