// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: gmeter

#include "ui.h"

void reset_pointers(lv_event_t * e)
{
	// Your code here
}

void restartESP(lv_event_t * e)
{
	// Your code here
}

void sleepall(lv_event_t * e)
{
	// Your code here
}

void time_plus(lv_event_t * e)
{
	// Your code here
}

void time_minus(lv_event_t * e)
{
	// Your code here
}
